dist: bionic # ubuntu 18.04
sudo: false
language: ruby
rvm:
  - 2.4.9 # oldest pre-install on bionic
install:
  - sudo apt-get -y install apt-utils automake
  # - sudo apt-get upgrade libstdc++6
  - wget https://archive.apache.org/dist/pulsar/pulsar-2.6.1/DEB/apache-pulsar-client.deb
  - wget https://archive.apache.org/dist/pulsar/pulsar-2.6.1/DEB/apache-pulsar-client-dev.deb
  - sudo apt-get -y install ./apache-pulsar-client.deb
  - sudo apt-get -y install ./apache-pulsar-client-dev.deb
  - gem install bundler -v 1.16.1
  - bundle install
script:
  - rake
